import Head from "next/head";
import PlannerInput from "../components/PlannerInput/PlannerInput";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1 className="title_text">Plan Your Day Ahead.</h1>
        <p className="title_description_text">Your Personal planner.</p>
        <PlannerInput />
      </main>
    </div>
  );
}
